[package]
name = "simple"
version = "0.2.2"
authors = ["Daniel Wiesenberg <weasy@hotmail.de>"]
publish = false
edition = "2021"

[dependencies]
rocket = { git = "https://github.com/rwf2/Rocket", rev = "3bf9ef02d6e803fe9f753777f5a829dda6d2453d", features = ["secrets"] }
rocket_airlock = { path = "../../" }
serde = "1.0.124"
anyhow = "1.0.38"
thiserror = "1.0.63"
log = "0.4.14"
